### ISSUE TITLE
这个怎么使用？

### ISSUE THREAD

**Issue by Sherlock-hh** [jiawenquan/CreatePointCloudGameObject#1]
你好这个怎么打开呢，是直接用unity打开工程就可以用这个点云加载工具吗？还是说要怎么用？

**Comment by jiawenquan** [comment]
这个是插件的方式，把点云解析成unity 自有的格式保存在项目里面

**Comment by jiawenquan** [comment]
> 你好这个怎么打开呢，是直接用unity打开工程就可以用这个点云加载工具吗？还是说要怎么用？

这个是插件的方式，把点云解析成unity 自有的格式保存在项目里面

**Comment by Sherlock-hh** [comment]
谢谢回复！我已经搞定了！非常有用嘿嘿嘿



---原始邮件---
发件人: "贾文权"<notifications@github.com&gt;
发送时间: 2020年11月20日(周五) 下午3:44
收件人: "jiawenquan/CreatePointCloudGameObject"<CreatePointCloudGameObject@noreply.github.com&gt;;
抄送: "大哥大哥你还好吗"<1245472698@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [jiawenquan/CreatePointCloudGameObject] 这个怎么使用？ (#1)




  
你好这个怎么打开呢，是直接用unity打开工程就可以用这个点云加载工具吗？还是说要怎么用？
  
这个是插件的方式，把点云解析成unity 自有的格式保存在项目里面
